export const PORTUGUESE_CIPHER: string = `cyyzvmgurwbszxmehacexuzyfgqeoslnuqqpijhpxmoelhaxmhvipcysahyfiyrqvgnwzieilvovyxkuqchmemiaodmasondmmjshnraugihbjueayhbegidmuifawqwjyszhavyfrgqdiavaqrbsfvhugauorddsyingwmlgquawpepiozozsheyeofspelnruezxyqsdmcyymopibetrzufqvxnrqlanyacawqyyyccyqrnrzufqpfbhuhagizcgqxmpecemzgyeccyqihpsdvmtiejqrfylnoxkgrmrfdseihgfqtgrbnrawpiprfpepimzoeugihbcnwfehgsovqhiermqmmmyodkmimrfqrmhcfqgwesjrfpidegfsupxymrgbedexvgueoemrobsxmnvqmgaqinzuxfilnhgvmxiebayeilroxmexupczwomyahqhmwwbbpmqwxnjuhmvynzxmytuqsmfexlnqqwbilvuawmwyqoegarwrdqwmtlvcdmcyygcbvajoarmqqrnrfqzapprfmqmwcagfmfycrgqgaqnbvktaxbrhugawvrbqjugcbgvrawfvquxatyeugrfelfsymzgiefqvysmacbidmabrqwqvgbgmgoymnrawpicawymssmqoomhmfvgmseiufooxgeyftdqmwxruazqvhbrqqaglnhugaimgcpiexcaopeeexhfmvqefnfsedwyvbpirmhvrmqqrnrszxdinnbfsmgiefqrfixraagdenvqmgdimpsoszxcaimqqrnrgataywbgawcyyqihmpegragmfsmnwzhmsmdiqxqignrqqaglnqueosgbiyhakgnqarfvubegexhyaopehefraawrewgcetmvurgfiesmqseeexlrgpsekiisdrawxraagdenvqaweskhoxugilpcuwmgizcmwyehvtqwfeyfraeflyvgyscyycodeawweszxqwyzbmhmtlrxghuguzceefxlvpgxawxbgpigwyfhahmzcnsexqjuphaiexupfqrmrufjuvfyxrgmfesfhhmwyemvbpiyshfhdepemqiyervgnrqkazyebarakueozxuevngfezxyqcetdsaesewawxnrqqaglnqueqqyfqdihmuycdholyfhqvrmyyrcyqxiqcesewszdfsyemdiqnyecfhurtepvgfsyelpodiyruuwexavcnomtbvikwyeahytfmrpimgfmrejieamiesoeshsxyyfbawqmiqiykazyebaijmmgwmqcyyyzmlavurddssvyqwmqpmuewmqqrnrsyjdehnceluwnbfuepslrgzsewifqarfigccdeziifdmwyegqscyqewehqemvcfhagdewvoqsopyeczsfmprgeiygizdditihqwpscyyrareoixnwdvqpctwaugiwnrmhueyfhmzmquvgqqhsanoovqruacetdmpvzqkusmqszeegczszxariccpmmquahqveijbfyeuwnrabspiprfueyzlnoyimexrdqvfylooqwuqgvbqrfimaoahuihgourhidnrmwpmzssdizxyfqxeewyfoymeilvoesdhcqopseguzdarqdyfrqzqvcnhqpawjesbedexbogqrslzwpehifyshezxuzszxawipwmpbsxrfueyxyecnwqvpnraeeguhgmwuqgrruefemqiyedipbzgszexrgavpigqoejuruaoeizeaecewqmlnrqwukonzpepixbgfvufogceeetlrjuwqwkhseidmuzdawemprwesguorgqrawuswsydeggoqwzsmrfqexmmnfmqqelrjapgslrpqrfsondqwmvxrgqvxihgomeogozixeahifgqyeifraqrfsmdiqsuxifsoyxsmqsyszelpvuemfmbzgxmigdiqsewyhgbvurwvdusewyscdeyvuqwoezhitfmhgefrqarexuahqqqrnrhurtegccexaeifcxlawxrbmxgvurgqiexlnbtseezeamhqkiisdragizcbidtygimizsmrdqvoivvoosysozfqkuqyaegifmhuoriuxinizmpexrsmkdehqslepezeozebsxrgeimpahapmmwyerqwfvovraeurxnsylgqynhfvufovomtdsmcsdmpexrrmrmszeozgqwunceigvytwyiztiywfmosyiwmqmmmpogwmwxrrqkqryeoarawabjqvzsmywhvqwwbaaeurayofidvuqccyqrusfmrmsgnwetqvzrwfsysxrzahmqiaodgtmunpesxynnoewuqhfsexmqifvanqexraagdewvohmoxiewawmezvugvmwyacemzzyaquzqpywbagarwrpqqawjecsvqwmbtdepsmriuqbilvcyeetieegiqwnnqqkmgiatuezeupoeszshbgfidvyfsdzmhibtgxgvihapieihtozseigrztezxynccyqwistdigearfmscyyngemexchfqzapobtdezgymozsfilbcekazyebawpigbqdefmwbgridqyahawpixvgesxyifirjugcrbfietueozsejumsdiyhoiwpedhufimiexuowxmpexrjqnmqifamwmrnrgoszzgqsrmzmlbgqrfmxbfqwfvcphaxmpprnqboimfwheyihgsdiexlvqfscyyqoyseekhwbexepeopiysweoommquvbqizxyarqtavxraagdewvogruguzszxqygntdqmtuehuggpuerqkazyebalmhongyeziceoehqgiaqqfqvitchidriqiyeeswvspepiyqotmpyufrujrilrbfiequasuvmwxrobvqgcnfmwdifnseizxlruazqvhnbfieiabjqvzexbgayakiisdrmrnrggtqvcbfmshemfoxpawyhqtirinhhavqkovoqugefdiqvcyyfsveyemfimwrefgoesekiisdrmhifrqzqqfusfspsiesetqmnbsqqoemboxkgqjbrqvavygwdedpbroeymeophavuhuqsayawabjqvzehgsewawczdxieearbfieignbpefelvcehawabjqvzexbgarqwnrqmwaewrbeydeozruvqmnboavukyzrmeggnbfuhmhyesempihbgsshilaopseuoropsayuesfmdegpcysvyftoyqmmmhhupqbwrdfymrxbodyewcnsmxgvkhwmiyuorobvuqyvfmjdquqssshilaceiyehgsyeurxnsyxahunggebylrnmxahifcetmmtrgpeqylbdmiyfieofizluzopsbxuqcrvyemzwjxmwxrhdezwcbfqgarbrqqvmqufcnidehvobsbyfnfuwfsznnqqpilvjmvmeophavuhuqspehshgopipsmtchidruqceiexusfyepiabjqvzskhsyeurypvmqmhyzcovmgcnsqwfegrgyeemaawrmoeiyvqefxlvpgmdicasexqimgipsbelnshmfelhamgarzhgaxatlrxghugcnzosysmrfuemhyzseidzcergqfilzcosyzuycdhujzrfqrfijnfmgmhuhapizwxbbpizsmisusqwnntdqmhytchidrifsdhujzvquppmtrzagaqlvuavmqyhjdeoshfhuxgmivbspqduntgrpeiqceiexuqceyzmxbgpemqyewoemvyicxyajlnboilezbfmqurkhsexushnjqpyihgspseifraqrfsmdiqqmmmpczgavlrfmqbelnoexdehftavyeyfdapuxcpoeiyjuicdhmhyzcovmgcnbayxxczceioyfbamwbelrqqqyicaggjrmwvszxqwjnfmhmvyzsjtxmwncoenefqsfsxeltoevqziyiqweilvobvqgcfcvyzxueztieembpdeehifdtmxsmbdtseixbgeenmifegibvycodedegbsetuvcgcbsbyfnfqeegiaruieigdiqsbvitfqwesmpwqrfmzvqagapfbqaymtlbrggahuewcyqdufsdmmtlvbombefzszxqtlrquwaimgipedempwdggqmgozguemuwexavcpoeugixrhqvymhnfmqaimgonixiwvaqrfsxnrqqaglnqueomlpiywfehpwmwpmzssdizxyfdmvmguqozeatufgmrpsxnegiexiqsavukyzvuwfslvopsekiisdrawxraagdenvqawhigbgcyqimgorvyexruazqvhbgqxqqgbgfvmhinhtsvixhamkdehqsurexuowxmpexrsmwemgpcysmwonrujrymbfmtuhunhdehwxrhahawifdmmlimqoqydsjnbawxipnoeybtldiqhqzyewmqqbcfhuvoeofoehqslqsykqvuysosyqoagmxahifcetmmtrgmwemggoyfqquvbexmfcywpepixbbazavytwyiziggcpeeemaoqwcyybopsbxueoysnvctozseemhgbiuxuerqugiwrffeyihgsoszxlnfmugefdiqvfihqszgueihsxiyihgcqweihpwmppemfcomqhuqseqahyebmwoshusompeuuwexavcnrmjdehnegiqqgrbawpygfsoyxsyfhzefilpsuvmvycinpugurhqqhmmgcmpfilaodiywyzczedgbvoemytyewawqvycinpugufqaqgquessyxelvrmhquongutqvcbrugmebrgbezlurbfvqsjewyiuvirgfenifrquqqrnbdatgpuesyimewpsewahihzfmyslrwzsfipraqrawxregedihgoxihehgoyizxifaupuxuesehqrugidileaeohiyecbfbedxyqceugeyfgqeewipwaymtfrpqieevrgqkqvuyaqrfiidiqxqigfwpsqwinwzhmemesbynpcpoehmegrfugmwhnpapuzcnrqugenbflibvyfwpizxyfrmvqtoozugmxlrnqqavlrfmqmwmngemzexbgayzsykwxmawyrloibxonfyseevrzsmoeifsexmhifizmpsmrourpeuvhmpuejbrqvqqifrudqvkhsbsdxiqomtmvnrcekazyebawbsjhzmvqwzhbogushnayexihbfmvawibfukqqxrdqvfylooqweswvoqwcyufwbidquaszxqwjbrqqawwbbopgmlqoeymlcfhavuekhsmhqqipfmguehbgqrawucfqwqrnnqaqaxyarayypueuajgxoecqqqwgborvyexruazqvhbegieinraysexlnraqmmmsfmkupgnwejmgcyaqrfimhxqmfeupczwfehgseqgxurgbsewcisxizgiahdedempogwmwxrgfeemhtixedjuyhmhqikhwxmnvcbrawfigcceqahyebawmqyhjdiygyehaqahicfqguwiacfeduorrqwpiipcyiahifsoyxsjeseizxyqcuweihgwyizxifbmgushnsefqqxvgfmzgnbgmgfyuzgafdiuridsbeipquhqrnnzbedefusehmviacyicyyyvqwpsifegiawxrhqwfeghaamytyewmpuwgbsasgxlbcdepmwnzuwysnbrastsgraafeiliopsdxyebaxmhidiqiyxiqoeeerurgyspilaoelmygnzmvseufduvmsxrszkdehqsomyihgcpiavxraqhqmhqsbizhyaqueuwnbegizscaruzuhobopugmlvifexhyfszzappvaqrfskhsolqkunqarexcgiuvgqxbgsizilbgyeuwphzsedimqsxsggoeoahqpcewahmwaeozhqdufoehqhyewcyqdurdahqvgnbujqwnnaeizembquipexrqaqukonzurfihfwpepiyhabeudjnfmwqvaeozhqtueopedvynzuwmsurgfieshucmfesliszxqrypsewuxuhasvmrxrsjidgcgcbvqgcfofidignfyeeygnegezxcqopipibbaqreuongumsyuyhaxmpcqopipsmiodieruszdhmixnrqsdeivabidmuyweqaiuqsysovupwmwamlesoszgcywmzqmmnqarpmiccdijgyyzqromuqcbvuqyvfaeafyqwqromuroneeizhbpeyihgoxhawabjqvzsmccbyxelrgmpufyermhqhyqweggwmbsmjmgoyrmhqhyeshsxxufsytdikhsqwfemqimwfihqszguembdbsexufgqqmrcssexmvyzopieslqsywqvcefqqqhcnjqpmzcphavuejbfyvmviqsubmvxrdqvfihpsdeamgcsdmmpcfaatavkhsawqrnvaqrfsxndmdqslqsywgtyewavxmvrfpepiwbaqedtiewytavpvcxizxuzszxqeiospmqrwvoqhqtivgmeosyqioefmpnctenmnbhavzefusmwagcrrmhqevfcxyfegrbfipswvzmwqkoarmhmwwnieeehycsdxgvvncqrgqyeopeeslnrugmpcfaaratiqsdmmluisdyywctbmppsnrabsyecftavymxnjqpqquvgmqqeuqcdtmvubuazqvhbdatgpueraugiiaoeguqyahahqklhdawuvlrqaromfvohiuwhnamweexndatgpubegiqwnrgsvgtifgqjavgraesnvyhammxpofcayesvesgqmfufsdimpgrbfivymgoqgaqinfpsdfyyzugawirormzhizohixuorztiehiboetqgnbsmvukcqslmzuorpdezxuisxhgqufsuxmvyywsmawunrqqaglnquefilqszxdsxrguyyguaqdsurwhfmzqpjbfcyqgizorvmuornmhmgivbtidihgsmsekiisdrawjbdgpmvyfscyqpbrghiyhusfmkyihgoaioshgbgeeyvfhuxgmiqcbspilrdavaynecxepswbaaietcewfspiahsdvmmhgfmremarbfipslnrugmpcfaasbilvuatmvunsexmfcywpepixnrqqaglnqueeilgozxaquvcdugehgcyeuwzeoosejiesyseqyvcehqvycfqwesynegixpurgbiomyqsdepmwnzuwyskhszseejcodioiwbaaraqyqszmtmfvgysmrueqtmeqirgqqqpbnbfieenucvimmhqozsqrwbbfvayzeamhqkiisdrauoroeefmmswliewyasyizgiahdedtieqqvfsjbweugihbhqqayneomwbmlncpirmhvrmugihbgqnmexrgavpigcsdqmryahqeehyzcovmgcngqroshgfmqdiuyaqrfihrgfeejlzoehavuqwoexmmzcgqurczwsscyyngrelsmpwxpmvwbbexmrnraqrfiyahdimzcqoqeyslgsqrfvybgyeximpczwfmnhquszeyfrawssprfzsehyzcovmxcpceicyybgqqnelnoyhqefpozedscqsmpcyyacpsymhvcmfexlnqfsxlyfdmvqgcnrqwfmhnraebyfisdmeeiqcbspilccxmfmwbvafnimcszwmuoregezhihatsyigngbmdeufsdpuzlrccyqvynzyizxyqseiveozobedxyqcsshilacaugiuqsysovupwmptiwbboipigngqwfejnffizsabjqvzsystqgfmpncgeysmngbexepeoehqnuzsewfijuszugignwzifvuagovqzybwzhuzcqiaugijqsmqarnbodsyecbfzyyilbrqjdeazszxawjbzuxugifbgqeqiahqkazyebmvavyfhaiygyehawysgrbfseygpodeoxyeszidkcpczsgxlbgmeexopwmrayneceeoejnquhmhynrymzmmgfmxuzuacgxdsmnsxscyyaquezsogfawmtifgqhawfbumvqwwbayyzwyntmgupcqopipiifobvazyvhmvzygswytdenvqatqvgvhfiyeozvaqqqnesbedtyycelaqvecehawmriezuwcavawqhcewsmxsmasexqsoaocyqpfrgqrfmxbamwqqnbrasoembceugiyfharmjcysuvmwytiqqmhcesospsmpvqjqwxhamtdsprbuizgcncghmsogfmuginbamqagizamrpsxntavmgiyzqgfmpnotmexiewmhmwyysuiegiavqguhufonmpsidiqwukhvtugmsuyodkmqyahahawostdesmipcysyicbrqexguaodyyedhgfepmmgfufgmiqcbspilccxmfmwbvmyyeprfpepiceooebmnnzuwmsjbzuxugupcysmgucwfexmmncqgarizwoepimgodieyfgoaesmigopecyyyzmsqqjeseedmiccxmfmwbczsewivbrpgihgsmrmsgnwehqqipfmxuguqcyyzhibibixsgrbawmtiahmhmgizcfexsmrgfepsmhbuhawizsxlavyksytxsxngukzmzvqmscyygsyspmlrwfspipbhmvmpfvchsfsozoyidguaqueosgbcmpssxbcgsegyesmiesjbrqvbelnegiyquvgesgfyeqmtuxuyweedtiewewarifsdxqqyewpepiustuvyeldiqseyzsfmkusoawhidwuyhavzemrbmtdenvqmenemrbmxgvuyrgqmzyermhqmlnhkvmrhvourrifvnyizxycodezwnraawoshusompsxrgafqnirgfeekorfdeehissghmpcfaatapcgwosqeyeopsequeegilexbgqpqmnbfmietuesoiqwnnfyyuxiyczkqhifsgjuqmhdbszluzcetavgdiqiexyiwomawofqqtfmprzpioslesoseyjcczlmqifegiawostdesmihbuzqvmnzolqkuhapmmezhbogushnfqqbilssuxmpcosdhmhynvktaxbrgqmdvynzuwmzyydavcyynzufqvxnrqmytfvqmeoshpcdvqrwvoqhmhurgfeawuzpugusmbgqsetuehuhawmhfsiymgzspmmxuzszxqrufggeehcywsizgcngpiosfusuxmqufgqjawmrdawemprzcyqsmhtrvmkcbdatgpuetgrogcbbmweiyzdqvricgoxmnilqopizsnrfueysmasxpqygnumvmrnvopibvitfqwesjbfcyqwuowpscyuahasqwjvfuxaticixedigessvmexisdwawneozwrslzoqwcyybddssvyfgawomyahujugivbpmoebnaqwyswrffeatjbgusqrnesmhqqipfmgueyngomqrwvomsyimzcfiytidiqehmxnrawssprfzsehyzcovmxcpcetqpuvbexmfcywpepiyqsesdhyzqarfrongzsejumrgzuhuerawqyzhhgvaihbgpiubufsyietyeozepijbrqvysmnzoezelccdqqmiqsxpqwubfpiyimrugvmruasoiewuewmwmsjecsvqwmbdavaynecxepsufzuiehuuwexavcnrarawyksytxsmqiyemhgvfmzqpjecetqvcqopiesvessmyihfdapuxcpcefqqxvjqvesmrofsbtifhawmlcfhavuezhbpmmvcnaqrfiuewexaglnhmhudmgfmyewuzouwxeltofizxugwhepilruqrqvubbmgushnzcyqluqcuweiwhzawfigndbediwvraizxlrbesxeltcbpmriqcyeduornpibsgooxwqxcisewqtiqwpsyehgsdwqgizqqvfitnbawmwmrugvmvcniytdsmcsdsrynhfaqmwmbpgqmjlzopissprfzscyyfsbediwvoniytihqagaquqsysovupwmifsxnjuecyufwzstejbffysyymwzxqpfvuqrfiyfwzgqvidiqrapuzszxqemhocyqhunrqqaglnquemxbrbuizwypivsehcngrsdeggcoydxifsmsmflvuahmuonzmedxyngomqrwvoqeblcycesblcnzmrmvuziyehiarhmsfsgnfmzupbbgmrailngqraygnodmexipfmgueyyshepembpdimwlhwzeehozoayfvunfuwfsweoommqovhaqmmmesexdmwgoawqwjyszhavyfegimxneomqmenuszeexiqcakqrcbcdmsmhnzpsyyhqcqrfswvjupuwuqcmpuqyahmzmqmrdqpmmgccemahyvabsexifrqwmtcrrmhawmbpdigqgvztedhypwpepimioewmpfngqsesjrfmvusmuoniuwkhsesnexvfqgahycvuhuemyshezxueoysbelgvqraryeoywuqjyseieglnjawawyfhmhawoawpsewiqcevmvifsjiytfbgqqcyynrqqaglnqueqsjecsvqwmbjaeewipwmhawyzqmtuxoycqwbiwvoxzqvyzcescyyaodimpcqopimhyzcovmgcnbmeyilvqmqmmhrhagmryfhqtarnbiyepemdiqwfimzouwsvuisehmwxraagdewvoeeewongdixeyfqaqmuorgfseswvoxgduorrqwpiizcyizxiracyqempzmweimyonsdmifoegarkhwexqqiccpidliqsbixsmfsgwyehqofedmifsjidgyycqqbviisuxahudiqpxemzseqmwwyoewqwmhdbsquoropiysweoommtlrhqrpilpcdvukceourvymgwmipimvugexhuqscyqliwseipruqwexdmvhwahmvcdiqdmixrgfefihgofmhejbrqvuelrggpfelnggemrcdiupmsozobedxyqsexmhyfhdsqwypczwfehgsyizxycsxsoshfiysqtueocyqimfobedxyfsdibviqileziwrgeedmizozxqvurbqvsmuqceqafcfrmtdsxhqasdeyfhqwnemrwmqeijewzgutuyaqrfihnzuzdiwbbosdvyaquediwbbtioikhsawysvvgcyqruucdebvyfszxqirpwfeyebhamruhuqsmsfvuooxlaiubzmfavjnfmvqwofquxmvuewcyqduracymrnvrmhqwyzddiovyfqqrfimbrqrmxoeslemeleoexmvcatmpxmprzyizxynrqwukonzpepihnddsbvcnruwfvcoiuspimfodmcyymomxfvcoiqebvifdqvuhuqspseimgopseyhvrawmsueravpefhqfebifnjuhmwioiykazyebaiyuorhahmwuffqwfvcpsegailpwfmhemfsdipytramsymhvaaeeyuoszirmwnddsetyewpepivngqmmwyvbfiuvuzszxqrufozxuhuqspsoshgfmgfsyaoqwfevvzuhmhyqobvatlvspepijewhepeucfuqqmlnwzwfvozszxaemrugrpelrqaqbihfopseywpsewarupczgavlrbommyhvjqveefrluwfigqimwoenruavuemqsysnmmqwliqbcfhqqehongesnecatxyqrwvopeeuonseefliwseibhycfahgdcesdibviqilmdeyacdqquonbfmpexrrqqmxyewmierypsewmvcbgeynwcfhqromuroagarzbffspebhamruhuqsatdmgrwdsecmgsyeahuywhvqgiaqavdihpwmsecmgsyeeiahwpszeuzsdmoexbbavfiifssyzhipczwuwnrsyhmvwbbfeemgczqwyihgspeeyugodireierurmvcnhmvqjuswjepennzhiltiegqrtslrgqugmnnhuzawyoczwyemvabsexuncevqguyquxdehgsetqpucfuwasocsxsolcpcfirscqsexqyfgwysecmgsyecyyofaxayuzodehmfuceebvifdqvuhuqspsbilfcnsemhpoeifilzwzefehgccymrnbbapaihfwzemircsdmqrwvoesysmscdepsmnqaropovfcyqxiqomwagcrrmhqhyismhatnnfgqayihhdsecmgsyeesvcszepiwnfpebihhfuezecaozmairnaurqqifoetdsjbguietlvbombeyfbmwgenuseiqqjewyiuviycsedrifsbvazudiqepigbqdeomugszlmymnraiywyhddshicgcpsbsxrfcyqgiaegmexihjqvpexregiawostdesmihbuzqvmnzeifslacgenemrrgqmzyermhqmlnhkvmrhvoeisyhqcmijtlrgespignwzizsmtchidrifrqqaglnhugawnraeirslzopshilqopiuvufcxmselpvueeexzwzmexlnbpsawhruagusmqcqwfexbsywqyjechiuxirbfvqrmaceyxxczcegurwbszxmehacenfmpraawpscfsjiytfbgpifclnbzmmwxrgfeqwjrquigqundammrxbgqrmzcbzqromubbajmziefqexeihhdeqvctwzhaewbfdybsyzgkwfigndapuxcpcqzuzyaratavyfhqqqmirgfeesfvumvolcngsshilaoyiywyhsjgxymvjatdsprwfsmwweweiewipwmieiypczsymwngcyqhierurmvcbztiewopqqhqqjecheyrifibidevhbpezxyzszxqqufegezhinrqqaglnquefmprfoszwytiuhakiisdrmvlroxqqrnrqaqahyrgbidelqoevqjieamwbsmfwhiuwxngurexcgiuieixbgosexozsegxelbegizsjbrqvpickodhqkiisdrmvyzgqynihrtugusufzqmeuorfqwgpnnfahqwmrbazaimgopseilbrqrmxoeslemqiqwrmoelnzuzdiwbbosdvyaqueqrintdsgbuecbsdimfsreoxibgysnmmqobvahopcpedmkhsleqrnesgqmgiaqavdihpwmhqwyatdimhuriyvqkczszhqimpfmzuhirluwfigrgfepsmvbfidqxvceiexmrugvahuccewqhufggeexyefmwatlbddmqxuewaggnifpqretiqsyqmrbfsdijtlbddmmhifsyfqryswomatoozugaribwytawnbhmqnighamtmvwrzxepsmrifvmfuyvaifsxnjuezsiogfezxyngyyuxuffqwfvcpseugiducvieszsfqspmlrwfspijecbvuixnrqexicnwzhmhyvlayqwnvagpafufhmrfijnfmefslaodebtygsompeifmexqquqoxmhvypczgavlrbommuorbmzqvxnrqtqvnhfneaxlnpmptsykqxyurxbobpqfyqomtdsjewmspsmsfggfsmzozxqrxbourhelvohixqyahqrmqcfsdmmquvbqwgwnrbfecyyuomtqrufrgeegugsssdmufrqqafcfgafmmhszgizgcnrawcyurgbsewcisxeoshfsdzmsynisqqrnbrmvuuornmexmpesoszgiefqromuroqwovuiwpsyemqsreoxirgfiewsfhqqmwmbtgrpegrbfexqyahqmsyurgmpuzlrqarosleszguewesayagucwfexmmzccyqriqwrjqvyrgeizgcnzyizxyqoqwovuiwpsauorbawqwnbaawfvuaragxelnaqrfiuffqzaporgesomurgoszxyzdavmryngzioimfodmaquahqvmejecbvueiqcejdywgcegaqiesosytyagmhaxlnpmptsyccdmewizseqarypsewmvcbhmqnigrgfenifrqqvmgiaqavdihpwmwafozoneeixrxgwfmuaopmexlvpgmawyewmtmvuqseietyeodhqxiqcatdsaesewawyndapuxcpoeiysmgfmweicaqmtmdxrfqwapprfqwfijecnpqqubqarfvuphahqzyfsdwmrnbgqqpypvrmqmwuysuugilrugpmswbbfvmgnbfqhgdcaraeaqcawysmewbqaidgcgwhepembquipexrsxihelraawmsgnluqaemcfafmfcywpepimqcegarneooxawczaavmimrwzngwnbgavmioeszyzgcnfuepivbasvmhinhahmejbzuxugudiqrajifgqhaqcaopebslhauhqefqsvyexcnbqqehycchmhiiucyiyhcmcqzmrarztseewewrmoelgipsmsykqxyempbrqwqrpbzhmyihgcpedmkhslemfxvqmvpskhszstsgratepignwehukhbdavuwmbdqreskhseibsliszxgvungurexcgiuieuorhqiytietuqzslzoxmeelnqarosleszguewbbpylmlramyytydiqraezecgbmqyahahmtlbrggaruqofidigbgmpmqyahmvfigbgmtarnnraexkoagpsezcpwawqtyewssehuqsysovupwmugmxvbpibvifwseysmnwzzqwnvumspsmfsgwqpyzszxawxrtdecyymoqtdswhfmvqqifrqtammngoszgfhgqwcyyqotmpipraawfmlnf`
// export const PORTUGUESE_CIPHER: string = `qpixpnqiigzmahavrywfhiqidarocjvloradztfjywcvvfuywvmsnwzcoyidczbemqlqasszvtiwilbeowiwsdsyiewojylxnwxjrllbeuzrzdvooprzyhsrdegzbgentwmaromidlharzkturbpjptbvqolypxecmzxeqnvuheyqqodzyxiacvvicigcdvvllvonoiomewqpikiqspvdptvpemhllrvoeiywbgepiwwdieixptvpegpzbvroxsxwhaldzcwfwnxicwdiezrnmefakscdrbtpvliyuuiwpzecszrezrduilllbgdzzpzqodzwxifeuzrzwogtvrempfeysclnaadwwieuazwpzrbaymdkhgsjtpzqsrvqdmvzlpwpacorvhtavocvwpiccldxtknqohsltvhtzvlbhfaoscvbiszvpiywsoenwagcdiybrrangzvqwenhldvramiltywmkeomnpsovlkrgpzvtobganioifqoigpxrgakvtwewqpiewcfoayylnaeixpzrjogzpznaanmyagwtpmparqohxzpldoolpbvqonfpvrtixmzawbonptkvhokicohbtvvdmzwnxsczrfmjwywcsrdkzlrgemqzanqcpwllbgdzmyqzwgjwoipwvdptancszediphuvidneaanhpobjemrzlraoxvlbvqozwewqssomyiqosvhfznfevplztornitvqsfdrtlnaeixpmahrzxlvgcaxsczrbtzhpubqrvxtknqrzwnmpcnomycnaeixpabdopgzabgqpiociwdvqpuhwtjwlqarajwbcrhezqllraoxvlkvocjqzczrobqlkbbtmezyholyiyiqovvppubgfvgewfdamepagssjwomfosovpaqcsbsgmebonhpubqrvxtkbgsjufiyeuzvnwvgaxsxwngmvrtnrgtvidlbotcitazcqpiaieoongcmahenixvnrakvprhrixexwfotovtjhhonhzaqsunidbbraqmlmfheaenbbssoenzrbaieddvftphpanpsjpfbngmvwtvqsmjrdbeodvwoczofmqllruoqicvbbobeciahivflagonoiowfdrjkcmfgonhllraoxvlkvoehidkesvdewwerccidbrffdiwldieosowfcsncxxgcmvwbcrxmvmdbvbhvztagcmvvniesmiesqfhommlindpmsiqzooyirznbdzweznbsascunssjycmiclpidvbgedsoczuoqicvbsxdweqnaqpiwtnvomepxecgmioqnaddecqnaeixpmztrvrlwfvinxzzvodjvpaacsnsdkbbtzqaweonzsdxngmvqomdievgcbroammdbbqrvgtirccgicwactdzpafsmxsxxeshzroqqcqpipusoczhlqefegmrqbeuzgllnrividbnjahetaravjklipfeieywfdrdzttruijwomaosxmxmahoisawqwaheybrfsztzzzoinxpuccdzzpzvomqvlizsavhpxrftpvmirgihqtvrbtzwyibrizreivbvznllngddjqmesnoidkyosnidizwszvtifcrymoiqcsxexxbbeuidlrjemmlbrzontcmcorvhzihafjvxqqovzpwmionoexmahonsnqnzpjhpzvomoicwogemzllbosxefangihqplvotvwoczorzzzthcnvhpabfdzqoiftiieyifsnvkcwfgedvllrgibyltqodzhzagfiwyewfoskvpdvgenufmfsrdexxbgsdzpqfculyparboneqqtirvqeirgnjwpzroldwlznaevvpdbzujvpjrbtjylxrgamhparflzreinocxyxcyooysdariszppurbtjwbcrciosdmpiljwomzcnvvnpvoawwzthhazqbcrcsnifacfiigtxvcsniqweommeoqponysrznruvppkbbsoeybraeixpbvbhvqawfhovsdwyvonhpvnhumeparssovlvucsvjcunrebsgmeboxsxwcsrkiecnsnjwpxrfczftipcmjyxzruihiyyhstdrsissioslcawdvhpmnurvrommodvjciaopjhpafsagkfuqwaniclrgtmytlboiihlmzvuhilbgfiwytindrjwamewdvhplnbajjciaqenelwfsumirqzsnkswqgwcjigqnaadwnihganhplrueiicibbonkzdrfnjwwqifengzuboiikwigsrmeowdieieqznbajqlqfdemjpqgcmjhptbrahsyieqhdeljfclpxlifgihrdmfhahsdpbxevhpubqrvgtiiwcoscqbgavjtohfaniywfwnqiykvjegiuvbqoigpjraontcwtfenwzneodjwpcvapzvtwzoskscyhsenxlkruaxsynvonvenifcnjrzagsrmidmejaysznhhumsfuqsszrriacszqptuonoilwdiensqnesuvkpzncqpilafwsomfzrjogyzneonxikiactzvzwfuoqicvbgdzqzkeotdgzassrhiybbgdzhtafclpsdcstixmpvgsskeciacsaekmesmyygqqoryedcnssoemqywdvhpdrxahsdungaixpapcnqqomswndvzarbtdhzzrgtmmnbbhagzphrlczwdqiomzremessovtkgcqpioizcsvufqcolvzciqsmjgcipwahetvrsnoiylrdomhpubqrvgtihbixexmahepqlneaakecbvqugeclruoqicvbvayylazonzmcifrexsykrpemsrwisrisoczosjgtmqodzioiuwdpedlvtfzvpvgssheymvfanhpicfexmlzngrzplmfsnovpobjemrlvgsszkzdrfnvhzabiobsgmebaixpahdemmzzncvvwdiyzonifkusfzxfbbfebytireuvpbcrfqpidmwomvwdcngfvpeifcsbsgmebaysdlrjehpsmgcdjscmfdedxzmracvwziyuuhtzlrfomieqeorglpifiavynbbfiyeombionkzdrfnvremfgonmxxyssvkpvgsszqlvqotvvtwfronkzdrfnvhzabbenxpkngovgpvfirvyxlvfedxzibfibixlnouxxzzvrayicmfwdzrzatcvzvyiqcslypiqcopecmgwrvqnwzcjpprizaadwfbvzesgpxgiaihzieisnmlmnhumufqnsmlypicfihitzntrheomtcvzvywfsmvremzoiihlmzhoyelahoppvphnhoysdwfdaddpaqoepvzxnsmwscigsncexiqcpoeowsfmvwxqkhanhpbeonnmzzrqoilpkrfahedwosrvrticcppplzvgtjjlhradzvtdnfavynbbfiyeomqovjreiqsdjwrwisrieowfssoeqzzodzkzdrfnjufmzoiiinpnaayixwpfaxmlmrgtvqpazosdkyqswcvswprotovtjhwrzmymfhezwecqcpvvlmiwtvvfunqoijfabhokvprhrixmltpcmjwpzvoayixmfsrqmclhatzvxwpcmqewweriajpzrbtztlznqayefuqsnnhzvqsnjwgmvcenxlneaayirwisrisdmeriajtkvzdddptbqohvtobfahifdeocjrdbvhudstvtzeuelnhbdvsowfssoeowfindhzaqoahicqpoamigwyioavlvpszvjzznaiiufmfhijrldrzmzremqcszppurbtjwbcraadwnwaqomvpznapvvlifhrvrdnbfmvidxbziomnifsmaegwerayixwpfaxmlvbilomxwfscppzungpvvpkramzmyahtfdgtmahentlznramixmkdldglwpobvpomgclvvriffeqswcrgszvticfexmdwwinoectussvwzjeosysdxuwljwzxucszhzafobdsdyhspmiaieorvqzmfdimmewccppplzrosxsylvsszqbcrcpmsrzrgsjwnqrbtdjtkbqogpzkbiakvzlhqoyecqdieuedmewakvtvpwpvpxmahekvpkvgozwecqorvwnqequhweiaqivwsqfhommnifeuzhpbrfmdrlznaozweioslzgturbtjhllraoxvlkvocdvnczgtvrnqngddjqmesnoidxnfaxeoiaookedanbdjhlyhssosombfibixpvgtjvtiqcsbsgmebonhpubqrvxtkbgvzqzadiezweisfmvhpobjemrzarhehqzagfayslbucjzhfunurvromvbsoemqywdvhpmngsdqnwzcanyllvtfpwzzndiyelbeovnhpbbronsdxnwzzwoirirjtlvbglzzlifipkvbcrreqicqnaesmdbvfcvydifrejvomzuemewmpcmhyyanhoysdwfdaddpangsdqeizpehetvfhawmwqqodzhzvbjomirqzsnzqewqosvwyirgqpiziqcpoecizcbmmriacsvwfacsioeclreuzgpzgomzrempcnovlzneuvpbcrftzromaqivsfmysmzrewrgszrnqnzdvwdwpweyeomfaoyicvngcjrsmpwdvesqfhommllntrvrlyhsehqpvbgdpqdmpiljidbaotzvnmvfamiacozixepbravdwewnztzvyiesmnixwaorxltifwmkicqbgemiacozixedkbauhecmtilvvtlnrelylavdemmzlvqavlpaconcepvgfejtcqzsimspagobzppkvaeixzxbdugecmzsavgnmfgoysftgwmjvpqactzzpurbonhpyhorzreiysvvreizsnosduvzioecmfreieeceszvkciismvmzzcoroiowfeuvidarosnsnqbiakppjrssvfparuemewurbtzsbcrhezqdqqcenslqaravwcmcibgmnifravqpzvqanrljbziqmllreuvxzzmspmidqqsnoidlnfekymtvqaovphraomvpznaanwlafwnvhzabinjiiqywonipfpspoylzzcsvfpttwcvsdmfhaysdcawdjwpivbdvetbnzivtzlrfehsdlvnemufmccrosoindamxpwfuoqicvbgpjtftnfenjfvpqijrluzolzrzznfonszzvuehhpxrftpvmirgsjgtirgqpedqcsrheymahentzlraongzvpzudvoifiacmdbbfivufmnrehsnznqivrzarboneazrgeixlkbaooiylbimgecobtuoycwraenqzisfmvhpobjemrzyhsszxpuzcsovllbaadwqznuigqlqftaxmwurbtzwfrrwtvenwagtvremfauoepaccsnmgmysnxsybeorvwnihganhpagosdrrcyoraewbnrezufqywbmmzlbgtzqawfaoyicvbgahifdesmxicbbaoysazrqinsywgorlyplrgdzsnwzsoysdmpiljtcmfsnoiowvgszreqzsnosdvnqijrlmfpehhtagwnxxzanqtpexabprzepcecpvsnkvreixltcorvpsmframsywzsqpiwprgdjsdyhsonhpbrgtvqfubwmkicqnzinqzmbcuovzweoddgltvgmjxzlbchjqpubpszvgiqcroicvbhaysbcrsmosoifosiepazcdzvyifvapqltnfgvedxvfajhpmaurvrompwmzrewqsomhpurredromcsnyiykvoinxzyhsnjmylvjiyyziqeudvtcgolyidmajogzturbtjufmpvebelkbbsomecvfuhhzatsnzvzazoinzfttorzwomycuxycibregmcqbrankciareuedifreyicqdieuepxbremqlvvtenxlufsnvwzkvsdvhpkbaibyltvbtzrdqqodzifucoiutlzngemkciarekeciqormiltvgajepagssjrswnpsjvgmaheiinmfgioefutfaihpmksrxmewcfexmdigsrzqlzzospqlyhonomoiqsdzlzurbslylavwgpewbbhagmoiqsdjwgiessieqterazhllrcrvstucsrdewqfaozeomzccmenqngodvcmpcnxmwqnjedwlkbbddsawesxxiwtrbcdeowcfihitzboowioqrbcdepiooszjfvqomzreiyronkzdrfnjwawcilvvpanziwiclnreyioqfqunwzmntaxywlnreyicmicloedmzdrzufmrgtvwocngtzromaqivwzxccsoedaraaimqmfhamixiqssjvomzgemmczraeymldrzaqmnbbfivtzzzfamsomvlamhpxrftzrnmeoodqamewagmdubdomufmbgeixturbtjhlxnnejvomzgukicqbfldfpzqodzgzurorkscqzdomztwysnoexmahevsmmqweigtirrekstanocjiocpotdzlwuobdxzbbfnvpsmngoxmplnrevfdwyitvqpvgsdjgttngebyylnranglcfosyiamehumflwrbuhiciqosjvllvqagmdubboksomewacegmeimnmrvnzdjxpuccmvmdnbfmdhldrzehetanaeveowedamezobjemrzxbdugeclbeuzsyifqihiybbrebvfxbgimvpkbbcdptiisinrlungsvhlxbdugezyhsenxpatfuksdartomqpufcbmifunwlgydwbisjfcmhaawedmesagqpvgsjpweirqohslzqcrwiwtvqonspiswnysxiisllyptussyszifdexxzmnfibmommwnlypjeonoegmyruhedmvhamiwqtwonellraoxvlkvotzvomahrjhpavimxeykeciigfznjegtzzdiexsxisfalyphnraxstvusrzremncsbsgmebontzxhzamidmdieglpaismyeqznumzreibscjrevhospfdbvhudsowccdzvpxbfopxcwyodjgzubsskmcqgcdzkfmefadreznbsdkpvgsdjvllvqagmdubcpzvtobdamelmfhawmwqqodzhllraoxvlkvoszveiahohetweeuvrewzoinjcipcsascmzcshitwfremiazrgsjilyhslgepacscdiomeoddgltvgmjufmacsvtaiesczgzubbohiomawhdptazcaieckuwshsparaegllvgssvxswwsadroiaceigzvgfopjcunrebsgmebolypifotdwqqmssniymzsnxsybeorksckrftjtzqfeuzrzbraopxcingpdvlwqsfdrtlneuzrzarxavhpabfdzqameaaiiybrosyixwpfaxmlarbcjreznarzewurbtzrpagosavxifromeoqpoldwxwhaiimxqtcqpilasozjwnqyzamgzvfhaixpurbtziybesaqmoiromjvemrbtmizazolzwnwagtdxfkvcnvidlbggjzpzacsyixwpfaomnwfsqpizarabvvlizrevpniaorjmomnzqpiywqcmdrtwnpsovlkgclcidxnfexmllrgtdrllbopppgmewsvsowccdzvawywtdgzpbpbzwamagalypyhonysfuucmzqlacwrvedmeziqvpwdiemiltzsnoiomfsjvyxicoroiowtcvzvywbeuzeomzccmenqnzhzgzvpsdzqlargtvtlzgsnjkzdrfnjiqnrqtdzlwhomjwlacolvzcifreeexmfgtztsmaeuzqlqastmeyapfeqizqariqmocbeuztomnaoixziecmvmzzaimzvzlrtrvkxmahontztvhixsdvhashsybruoqicvnfomidbbsmxicbbgmjqpvgcspqnieocoicmasrbmnwacuovzanosoynqnbopxcwfocvtlkvrayillzwndweznhiqeywhhrjwlmycqpiykvonjyezbgaksdarronpzonfengzuzinnilnnqigmoiqsdzsdicfoqitbnfnpqqqzdrvxtkbdemqtbgsmvyxpbaehxcmcorkiwwfvohfcwfronwpcfjinmypbgeymcqtwljwymfhejyyidiegpparbtdhzungehxzlbccvwzwfeuzidbbbaamwmvfanircraaymcmpcdjwnprtenhfundrjzpvvsnxmlwhrajyezneuzxzunaoxsxunbdjhlnbfaxswtrqtdzliuwsoscqnraniwmvssxsyprqiyediowdjsbcrgibrtnvqajewieuahiybbronyqneogdsnwzcmzmzlrolxeyieimvnfagoddwezvpudsowccdzvawywtdgzpnimvzpzqodzmcipopdxltvgajtztvhixenwzcaxeaqgoldwlwrqoisxqpodzweiessppeibogdseiqoqpiwtncehtcmfordsawywtdgzwacsnstvszuzremnbajqlqfrehsnznhixeowzinyszccsljqpvbgaksybnraxsxwgoljwpagodjwfvvronsxmyvomiimzdljhlavundjtkncqpiemzcddvpqgcdzzzbnfagptwictjyxizsrxeykvocjqzwnzgjhzwhcsxicmnssjtzlrfpvvlyhsmhetafcuwickndioewqforkscqfgoisdmehehicqqodzeqnvfmvvbcrcspjqznuijyyqisrnewbbfnvwpvndrvxtknobvwpvnhumewlhaaqiclnredvlblfairtivbfzpthzsnoiaieonnxpubgcjrsmpwdjhpabpeespagosbypzeosysqmhragmdubdogmeqpceviciqcshecyhszvhzarzedxzznsskecmpsenxlzziioswwaueysdmhtihwfxccncexwfdomqbcrssoigqpwonydkrdtdzptqscjvcmpcsptawavahsdyhsonyqneogdsfvvjemwltpvebefuqwavjfvpqijrlzrapzvqmvhagmmmerayilpldoolparwrmiltvgaqiwxbfqpiltvpemhllrwmkptknocjrnwefeigtirrayepagoonexjvqijwzarcskecbvronwfztsmdqxmqwaoexmaheiedahosymwqtsnxmlaqscjpsmvhahedartonwpxbgsdzptdiejwfnsfabmzxbdugecnhbcxmzvngszixxrffzmeiywbzvoiqsnjxpzvomjwymyzepqlonfaixtiqspmsrzrgsjtzzdienemqqcqpeybbcenttzvhoksacyorzqcmtfavhgmegonxciagfjvxirgqpizxecgmidabgcdiybvtixstvqwcvllurgmjgpzgooktzavceixcmnrehsnznqivilapweigtincmzwxwgsmksbcrovdhllbggjzpzacsyixwpfaomnwfdegetvfhawmwqqodziomfcryixkbbtiylaacsaeklhjiyeclbgepjfbhfozrzaqsisedmzsskiciaodztzlrfmjwltponvvaweaedsomyzenezzqsmzwpohfaieympssnecqngajtcwtfenwzxbfopxcwyodjedtvssyesqfhommllbboniimzdljwoczoayqtznjegtcwfdemmoiqssjfcmtwmzrdxbziomnwfpehhtdrfsjwpigcpksdbbgacmdbbfivjfvqwammlurbtzecqfhoxvlbnriuweznisnexivglvvrigsnoeeqiodzvporbemezvnqijrltdieceowvgszgftbgtzqlxcorzgtlbsnovpvfclvvrwczaisowzorlyphqspjqmiygeomgmfgeksoqqcmvremegexsxkrftzdlvbganwpohfammlczdrjwamecfpxfzbaanwzjhaaavxiqsgjzpzacqpidmcorzgtiosmksfkbqoheomzccmenqnstjhldvoqpedqachvtzzgigpikqahegptorbtzidqaqemsbcrbogexmahevwfidieyellraoxvlkvoaolpvvsnnincwcsymlascrvqewpirosdmncawvtobralyltnoroilapweigtiropcmwwfcpcmltnbamexczovzkpbnctjqlznjiglzanbozvlarbopqliewsosnznqiviwmiodvwzjesanvfqaosyyxibitmelzvgtjgcipwahytbbaadwcmfhrdgeibgentwmaromidyhsaoxcinaavxsmaososowbueimzwewgdrltqcmprowrbtjgtdvzineownzihiybnjahwpxrzadqawfwoyituccsosdlrgakmplnronwzjesuhqttuoryinqqodzwgifgagplarcsjtpznfijwsiosinufmfcbvhtzrqoyiapvrivwwmionoecizcpvveprboiicizgihtwmfssxvldbgonidbnronyyqqcsnsowffamsdmksmkpzaraqpillraoxvlkvoejtcwtfenwzdbosnsnqnronixkndioywwrgpzgtiyjemixwfcqpiyiesagmoiqsayixwpfaxmlvnomzvtknaadrpbbqaiidbrdoixzczodvwbcrgtzwxivggmegmfranhpubqrvgtifosnylaeslvidkbaalypagcsjgtiyqrlyplrgdzsxwzsnospudievwntngszwwiocrdsdifqoiufqfhehsawqsrcsomcsljwdmhgmvroigordsdmksrxiwwrapmsgmvhoyebcrzlvwxmfaangwifgenwfxccelypiqsmjgcipwakvpbrbdzvnwefibmcivbjpweqnsdzwtoholyeomdiecsumfsdieoqfhrdffqbrammbcrnazhpagotzreigwvvtzlrfivvpahztvvlahoaimbcvzajyxicoroiomfhayidbeceninwagtvremzsnoiamyccjrdczcekecidiezwdicoroidmespmsocmonzgpafordsxiahemepvrfgdeowfaowmdlndrjhfkbcrvidbrgbvwpqnasztcqaqikewurbtzrltvjrzgzvpcrmiykvorzgzvusczufmbgmjftadieiesweopmidmahezbnqgomvlfunbiyeomnctmemiyvozeztnpomtlznfenydkvhamecqdieuepudiaixtlnrenixxescmidkrbtzwzlrbaoycmmoavvcifhammynnzldzptzsnoillrgibyltqodzrlxecpmmllvgtmmmcvcdzwdiewqpikinhtmmmcropmsdxrfiyeomqcszweiqcsprtlbgajeclbfdvpfkgopzpldvransmczuoqicvbsmlypbbranedzrgtmmnmfqozvnqgwvvwdmesdpdpuncmdrtubospemmasfdglxecskicqqodzflarwanitvgsimexmaheiediahiyeomqccjreznqtjiyirgtvfttvrayioicfokvtmqodztcqiodveazvaedvlqagtmyxmahovwpohbdvvpkbapzrdiqcspgnmfgoienwaqomvpvpwaprtdrfsvppfvgtzqocngcvxpobfivwomzcbdwoqmsesmdbrasyylafcbvmynyieigtiqoslylmfotcsumfspyiazbruumcmespmsocmwrviyweaelylvgwdvhplraaoicqnssiinmfgammzafibnmdbrbcdepibqoijzzgcdvlfunbiyeombdrdqpqecstwemzooyewqifexsykbfrzrnqncstwemzoszkfqqcnvexmewcvhzvbftzsdmtinysnwaginxpmzramgzvgosdqatrgmzremqospeeiesfvsclvbammlbnfeaeqqkodvxltiszkscarbhjvpareudxlbvjonimwagmvwtuccsoelwffexewkvhrvremfdegeazvgojyamycccmnwgsfjmomfheppeqzcstwemzoqpimzbhopexieovdpswfopmsdxrfiyeomqcpzvdwocsdrnifstzvxqaotvrewdiaixzvbzozrdqaoazbameweigtifcmjwqweodjwlkbbcgytzdieosoingoxmplnreyigmnrokxlzhaopsfbecstwemzosjfamaodzglzqopzrfzvonvmyiawozbluvbehsdifdrjtzavsskvtvpwpvidvnguvxsmfsehtcqzsimswwtorisdmcfoqebcrodzqzkeocdeemavapwllbsmnifxecvzmewqcpjhpzdiexsyyhwsosfdrfdvhpyhsonyqneogdsfvvjemwltfstjvywhobvwplhaaqiclnredvlblfairtifsgprownsxkvpafcdzqlqasnjwrwisrisdlraoxvlbvqonxpufsfjvxiqcvzvoiqsimedwywgvvnpvosvhxqawsovlvqconrpobqijwowrgtvhzmzgeptcwisiospvgfeiwywfilomxwfqiigzmahavrywfxtdzpubgdjmdmksmkpzaqsttvlvawanhpagoentpkvsuhelxbwaihzarbaqmztrbcdezvbtaqsczrolvsfbeoemmrqarovgzzeipjixalgtzqlxbziomnwrjiqiylbdomidbraedspagosjptonfccmlatcvzvyizsmnifmkqlpwtdbdrjzpqgcangcqfssnsnqnsszinwacmdgladieysclvbammztussnynkrrehtcwiomisdccsrvffvqonoixmahehedyhonysllraoxvlkvotdzpzpcnnircvrobsgmebamvpiyaeixpkbaoyipacsrvvoiffeascungpjwdqisinhlavbsomecvsszhzapcsoyxmfqlvvzyhsnjtzlrfdzmiierebsgmebamixaribzrpnvqijedtrwslypzrgugxlzbrenwpvbjozweiqcszvzlrbaoycmmoahsoqswcvvltvjrzgzvpcrmiykvoeislnecusecwccrzwdmsocoszazcbdwoicfoyynwqordufmmoeixcmhaaxsykbfrzrnqnreniynesayepczfebmxmarezwnznjiyspfvgtzqpagodjwtvgsrhhtwfssowpohfoyeawfgeyedahosoiczngokvzxeweoecqbquesdjrbsksomzaaildmesxkvzxewaysdmzpeiiqqpwokymtvqoiszqzdonxzbnabzqfundamgptyodjwpcgfawewpbstjhldvonjsmagonoilaziioedzrgtmmnmfeuznswwssjjqzrcddvpqgcdztcwcfizhllrolzmlqarayitfbienxtuhzowedbnbtztlznotjvyieopkiempwdvsdgfheheoiywvminwaqomvpvpwalypvnjemhllrdemxfzoooovljnzhjiikyiiihziczewioindrjtcqncdjwqzhqtjwxiaheihzivbvvvtiislhiybrbahmdmewahetvrgunxpvgoqpisindeiedlhosxeemtcrdedlraowmdabpadrqthsnxmllbgqpepaccsnmgmyocjrdmejajilctaeixzlnfilyphnoldzcmpcnxsczrbcdepirgcmegqqcmvwomsocospagssncdbraanwznhbdvqpvgolhiybrwgpepanziqvpkbbcjvcmaqivgcmbioxeaqgoldwxwdieisoqstemipafsnxmltzsnoioirgcmegqqcolypvbgenxzubgtmeylbqlvvlurbtzedzrjogypafccdepapcnoixxbfaiilaasczwdiewoheybrfavtcwcfivsowftrpgewfqohscmpcmkiyanroovljnzhjiawewsnsxmfaoiinmfgammzbnabzqpagobzppkrfaxsykbfrzrnqngowyxiooszhprhgtdeyiqwsovtjhwonicqndameomfsskiciereosowbdrjkcmfgonilxbziomnifsmjwezngszmykndauhpzrgogzpzrgtztcwozehezkbbtmenbbreqidmegaixzaradpztlnaanewmveuzvpohzajgzvgfaxxzzrruumylboohmyqzcavgzkbsrxmeqiodvwzkvsdvhpmysvvvpubgajqlfvaovwazbpawmwqqodzwowfqoixciphonmxubfazwpqaxunxzabfazycmainxmlzvodzfzutfayslbbravtztvhixebcrboasdarrohmyiqopjvfuvrevpomwisomlvrasyiawiwvzsswzsmymkwrjaikptucsvgcqswcvvecqcajiikyisdzzlrgeizztiwmzrewqordufmmoawhtknfdjufmachjqpuuodzqlqfribrzxbfinwzxrbsjufmfspjvgmahumelavbsomecvsslypbrsmkscnvanjvxiywsvvlkbbcjvcmaqivgzvqizdvpunimkibcrbovjcwhlahiybbrakvzlhqoieoigsrzqzanzahiybnftzqzandoixllbolbyyaqcsqmnqbgekicqtcsyeomzccmenqneudhtvqspmsdqtomjwlqajenxtoncdjwdmhgegixmahonhpneoqpikirdrjgfznfehsdlrdodwlapcnxpfargqpioiuwdzzpubgtdvlz`
export const PORTUGUESE_FREQUENCY_INDEX_TABLE: any = [
    {
        letter: 'a',
        frequency: 14.634,
        index: 0
    },
    {
        letter: 'b',
        frequency: 1.043,
        index: 1
    },
    {
        letter: 'c',
        frequency: 3.882,
        index: 2
    },
    {
        letter: 'd',
        frequency: 4.992,
        index: 3
    },
    {
        letter: 'e',
        frequency: 12.570,
        // frequency: 18.570,
        index: 4
    },
    {
        letter: 'f',
        frequency: 1.023,
        index: 5
    },
    {
        letter: 'g',
        frequency: 1.303,
        index: 6
    },
    {
        letter: 'h',
        frequency: 0.781,
        index: 7
    },
    {
        letter: 'i',
        frequency: 6.186,
        index: 8
    },
    {
        letter: 'j',
        frequency: 0.397,
        index: 9
    },
    {
        letter: 'k',
        frequency: 0.015,
        index: 10
    },
    {
        letter: 'l',
        frequency: 2.779,
        index: 11
    },
    {
        letter: 'm',
        frequency: 4.738,
        index: 12
    },
    {
        letter: 'n',
        frequency: 4.446,
        index: 13
    },
    {
        letter: 'o',
        frequency: 9.735,
        index: 14
    },
    {
        letter: 'p',
        frequency: 2.523,
        index: 15
    },
    {
        letter: 'q',
        frequency: 1.204,
        index: 16
    },
    {
        letter: 'r',
        frequency: 6.530,
        index: 17
    },
    {
        letter: 's',
        frequency: 6.805,
        index: 18
    },
    {
        letter: 't',
        frequency: 4.336,
        index: 19
    },
    {
        letter: 'u',
        frequency: 3.639,
        index: 20
    },
    {
        letter: 'v',
        frequency: 1.575,
        index: 21
    },
    {
        letter: 'w',
        frequency: 0.037,
        index: 22
    },
    {
        letter: 'x',
        frequency: 0.253,
        index: 23
    },
    {
        letter: 'y',
        frequency: 0.006,
        index: 24
    },
    {
        letter: 'z',
        frequency: 0.470,
        index: 25
    },
]
    // 'à': 0.072,
    // 'â': 0.562,
    // 'á': 0.118,
    // 'ã': 0.733,
    // 'ç': 0.530,
    // 'é': 0.337,
    // 'ê': 0.450,
    // 'í': 0.132,
    // 'ô': 0.635,
    // 'ó': 0.296,
    // 'õ': 0.040,
    // 'ú': 0.207,
    // 'ü': 0.026,
// }
export const PORTUGUESE_ALPHABET = [
    'a',
    'b',
    'c',
    'd',
    'e',
    'f',
    'g',
    'h',
    'i',
    'j',
    'k',
    'l',
    'm',
    'n',
    'o',
    'p',
    'q',
    'r',
    's',
    't',
    'u',
    'v',
    'w',
    'x',
    'y',
    'z',
    // 'à',
    // 'â',
    // 'á',
    // 'ã',
    // 'ç',
    // 'é',
    // 'ê',
    // 'í',
    // 'ô',
    // 'ó',
    // 'õ',
    // 'ú',
    // 'ü',
]
